# Generated by Django 3.1.3 on 2020-11-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='current_location',
        ),
        migrations.AddField(
            model_name='package',
            name='current_box',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.box'),
        ),
    ]
