# Generated by Django 3.1.3 on 2020-11-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201106_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
