# Generated by Django 3.1.3 on 2020-11-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.company'),
        ),
    ]
