# Generated by Django 3.1.3 on 2020-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20201107_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
