# Generated by Django 3.1.3 on 2020-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_master_instance', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
