# Generated by Django 3.1.3 on 2020-11-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.company'),
        ),
    ]
